package DAL;
// Generated Dec 3, 2014 2:40:05 PM by Hibernate Tools 4.3.1



/**
 * TblDocent generated by hbm2java
 */
public class TblDocent  implements java.io.Serializable {


     private Integer docentId;
     private String naam;
     private String voornaam;
     private String email;

    public TblDocent() {
    }

    public TblDocent(String naam, String voornaam, String email) {
       this.naam = naam;
       this.voornaam = voornaam;
       this.email = email;
    }
   
    public Integer getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(Integer docentId) {
        this.docentId = docentId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


