package DAL;
// Generated Dec 3, 2014 2:40:05 PM by Hibernate Tools 4.3.1



/**
 * TblLokaal generated by hbm2java
 */
public class TblLokaal  implements java.io.Serializable {


     private Integer lokaalId;
     private String locatie;

    public TblLokaal() {
    }

    public TblLokaal(String locatie) {
       this.locatie = locatie;
    }
   
    public Integer getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(Integer lokaalId) {
        this.lokaalId = lokaalId;
    }
    public String getLocatie() {
        return this.locatie;
    }
    
    public void setLocatie(String locatie) {
        this.locatie = locatie;
    }




}


