package DAL;
// Generated Dec 3, 2014 2:40:05 PM by Hibernate Tools 4.3.1



/**
 * TblModule generated by hbm2java
 */
public class TblModule  implements java.io.Serializable {


     private Integer moduleId;
     private String naam;
     private int docentId;
     private int lokaalId;

    public TblModule() {
    }

    public TblModule(String naam, int docentId, int lokaalId) {
       this.naam = naam;
       this.docentId = docentId;
       this.lokaalId = lokaalId;
    }
   
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public int getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(int docentId) {
        this.docentId = docentId;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }




}


