package DAL;
// Generated Dec 3, 2014 2:40:05 PM by Hibernate Tools 4.3.1



/**
 * TblStudent generated by hbm2java
 */
public class TblStudent  implements java.io.Serializable {


     private Integer studentId;
     private String naam;
     private String voornaam;
     private String email;

    public TblStudent() {
    }

    public TblStudent(String naam, String voornaam, String email) {
       this.naam = naam;
       this.voornaam = voornaam;
       this.email = email;
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


